In [26]:
%load_ext autoreload
%autoreload 2
from align import *
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [33]:
hs_seq, hs_header = read_fasta("./data/Homo_sapiens_BRD2.fa")
gg_seq, gg_header = read_fasta("./data/Gallus_gallus_BRD2.fa")
seq3, _ = read_fasta("./data/test_seq3.fa")
seq4, _ = read_fasta("./data/test_seq4.fa")
seq1, _ = read_fasta("./data/test_seq1.fa")
seq2, _ = read_fasta("./data/test_seq2.fa")

In [18]:
g = align.NeedlemanWunsch(sub_matrix_file='substitution_matrices/BLOSUM62.mat', gap_open=-10, gap_extend =-1)

In [52]:
g.align(seq3, seq4)

(17.0, 'MAVHQLIRRP', 'M___QLIRHP')

In [27]:
np.ones((len(seq3) + 1, len(seq4) + 1)) * -np.inf

array([[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf]])

In [39]:
seq1

'MYQR'

In [40]:
seq2

'MQR'

In [41]:
g._gapB_matrix

array([[-10., -11., -12., -13.],
       [-inf, -12., -13., -14.],
       [-inf,  -6., -14., -15.],
       [-inf,  -7.,  -7., -16.],
       [-inf,  -8.,  -8.,  -6.]])

In [51]:
g._gapA_matrix

array([[-10., -inf, -inf, -inf],
       [-11., -12.,  -6.,  -7.],
       [-12., -13., -14.,  -7.],
       [-13., -14., -15., -12.],
       [-14., -15., -16., -17.]])

In [45]:
g._align_matrix

array([[  0., -inf, -inf, -inf],
       [-inf,   5., -11., -13.],
       [-inf, -12.,   4.,  -8.],
       [-inf, -12.,  -1.,   5.],
       [-inf, -14.,  -6.,   4.]])

In [46]:
g._back

array([[-inf, -inf, -inf, -inf],
       [-inf,   0.,  -1.,  -1.],
       [-inf,   1.,   0.,  -1.],
       [-inf,   1.,   0.,   0.],
       [-inf,   1.,   0.,   0.]])

In [43]:
for i in range(1, len(seq1) + 1):
    for j in range(1, len(seq2) + 1):
        A = seq1[i-1]
        B = seq2[j-1]
        
        

M
M
M
Q
M
R
Y
M
Y
Q
Y
R
Q
M
Q
Q
Q
R
R
M
R
Q
R
R
